export const eiscpMappings = {
  command_mappings: {
    "system-power": "PWR",
    "audio-muting": "AMT",
    "multi-zone-muting": "MZM",
    "speaker-a": "SPA",
    "speaker-b": "SPB",
    "speaker-layout": "SPL",
    "master-volume": "MVL",
    volume: "MVL",
    "multi-zone-volume": "MZV",
    "tone-front": "TFR",
    "tone-front-wide": "TFW",
    "tone-front-high": "TFH",
    "tone-center": "TCT",
    "tone-surround": "TSR",
    "tone-surround-back": "TSB",
    "tone-subwoofer": "TSW",
    "sleep-set": "SLP",
    "speaker-level-calibration": "SLC",
    "subwoofer-temporary-level": "SWL",
    "center-temporary-level": "CTL",
    "display-mode": "DIF",
    "dimmer-level": "DIM",
    setup: "OSD",
    "memory-setup": "MEM",
    "audio-information": "IFA",
    "video-information": "IFV",
    "fp-display": "FLD",
    "input-selector": "SLI",
    "recout-selector": "SLR",
    "audio-selector": "SLA",
    "12v-trigger-a": "TGA",
    "12v-trigger-b": "TGB",
    "12v-trigger-c": "TGC",
    "video-output-selector": "VOS",
    "hdmi-output-selector": "HDO",
    "hdmi-audio-out": "HAO",
    "monitor-out-resolution": "RES",
    "isf-mode": "ISF",
    "video-wide-mode": "VWM",
    "video-picture-mode": "VPM",
    "listening-mode": "LMD",
    "late-night": "LTN",
    "cinema-filter": "RAS",
    "audyssey-2eq-multeq-multeq-xt": "ADY",
    "audyssey-dynamic-eq": "ADQ",
    "audyssey-dynamic-volume": "ADV",
    "dolby-volume": "DVL",
    "music-optimizer": "MOT",
    tuning: "UTN",
    "tuning-main": "TUN",
    preset: "PRS",
    "tunein-preset": "TIP",
    "preset-memory": "UPM",
    "preset-memory-main": "PRM",
    "rds-information": "RDS",
    "pty-scan": "PTS",
    "tp-scan": "TPS",
    "xm-channel-name-info": "XCN",
    "xm-artist-name-info": "XAT",
    "xm-title-info": "XTI",
    "xm-channel-number": "XCH",
    "xm-category": "XCT",
    "sirius-channel-name-info": "SCN",
    "sirius-artist-name-info": "SAT",
    "sirius-title-info": "STI",
    "sirius-channel-number": "SCH",
    "sirius-category": "SCT",
    "sirius-parental-lock": "SLK",
    "hd-radio-artist-name-info": "UHA",
    "hd-radio-artist-name-info-main": "HAT",
    "hd-radio-channel-name-info": "UHC",
    "hd-radio-channel-name-info-main": "HCN",
    "hd-radio-title-info": "UHT",
    "hd-radio-title-info-main": "HTI",
    "hd-radio-detail-info": "UHD",
    "hd-radio-detail-info-main": "HDS",
    "hd-radio-channel-program": "UHP",
    "hd-radio-channel-program-main": "HPR",
    "hd-radio-blend-mode": "UHB",
    "hd-radio-blend-mode-main": "HBL",
    "hd-radio-tuner-status": "UHS",
    "hd-radio-tuner-status-main": "HTS",
    "network-usb": "NTC",
    "net-usb-artist-name-info": "NAT",
    "net-usb-album-name-info": "NAL",
    "net-usb-title-name": "NTI",
    "net-usb-time-info": "NTM",
    "net-usb-track-info": "NTR",
    "net-usb-play-status": "NST",
    "internet-radio-preset": "NPR",
    "net-usb-list-info": "NLS",
    "net-usb-jacket-art": "NJA",
    "net-service": "NSV",
    "net-keyboard": "NKY",
    "net-popup-message": "NPU",
    "bluetooth-setting": "NBS",
    "bluetooth-internal": "NBT",
    "usb-menu-status": "NMS",
    "usb-time-seek": "NTS",
    "connection-usb-device-status": "NDS",
    "usb-list-info-xml": "NLA",
    "usb-list-title": "NLT",
    "usb-select-browse": "NSB",
    "internet-radio-info": "NRI",
    "usb-copy": "NCP",
    "account-info": "NAC",
    "ui-type": "NUI",
    "album-art-display": "NAD",
    "list-url-info": "NLU",
    "playback-info": "NPB",
    "album-art-format": "NAF",
    "reference-info": "NRF",
    "file-info": "NFI",
    "multi-gateway-status": "MGS",
    "multi-gateway-volume": "MGV",
    "multi-device-info": "MDI",
    "multi-room-name": "MRN",
    "multi-group-name": "MGN",
    "multi-zone-info": "MZI",
    "multi-speaker-status": "MSS",
    "multi-zone-control": "MZC",
    "multi-room-mode": "MRM",
    "multi-mute": "MMT",
    "multi-room-repeat": "MRR",
    "editor-version": "EDV",
    "editor-application": "EDA",
    "editor-command": "EDC",
    "editor-firmware": "EDF",
    "editor-extension": "EDE",
    "play-queue-add": "PQA",
    "play-queue-remove": "PQR",
    "play-queue-operation": "PQO",
    "album-artist-track": "AAT",
    "album-art-link": "AAL",
    "audio-track-info": "ATI",
    "audio-track-menu": "ATM",
    "audio-stream-type": "AST",
    "play-pause-status": "PPS",
    "play-pause-display": "PPD",
    "next-guide-up": "NGU",
    "next-guide-view": "NGV",
    "next-device-name": "NDN",
    "next-guide-type": "NGT",
    "network-friendly-name": "NFN",
    "network-wifi-password": "NWP",
    "network-wifi-update": "NWU",
    "ipod-mode-change": "IMD",
    "ipod-mode-change-usb": "NMD",
    "cd-player": "CCD",
    "tape1-a": "CT1",
    "tape2-b": "CT2",
    "graphics-equalizer": "CEQ",
    "dat-recorder": "CDT",
    "dvd-player": "CDV",
    "md-recorder": "CMD",
    "cd-r-recorder": "CCR",
    "docking-station": "CDS",
    "amplifier-operation": "CAP",
    "universal-port": "CPT",
    "ipod-artist-name-info": "IAT",
    "ipod-album-name-info": "IAL",
    "ipod-title-name": "ITI",
    "ipod-time-info": "ITM",
    "ipod-track-info": "ITR",
    "ipod-play-status": "IST",
    "ipod-list-info": "ILS",
    "dab-preset": "UPR",
    "dab-station-name": "UDS",
    "dab-display-info": "UDD",
    "av-direct-mode-operation": "ADM",
    accueq: "AEQ",
    "auto-power-down": "APD",
    "air-play-setting": "APS",
    "audio-return-channel": "ARC",
    "audio-scalar": "ASC",
    "av-sync": "AVS",
    "battery-charge": "BCS",
    "hdmi-cec-control-monitor": "CCM",
    "hdmi-cec": "CEC",
    dirac: "DSS",
    "pcm-fixed-mode": "FXP",
    "hi-bit": "HBT",
    "hdmi-signal-format": "HSF",
    "loudness-management": "LDM",
    "lfe-level": "LFE",
    "lip-sync": "LPS"
  },
  value_mappings: {
    PWR: {
      standby: { value: "00" },
      on: { value: "01" },
      query: { value: "QSTN" }
    },
    AMT: {
      off: { value: "00" },
      on: { value: "01" },
      toggle: { value: "TG" },
      query: { value: "QSTN" }
    },
    SPA: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    SPB: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    SPL: {
      surrback: { value: "SB" },
      "front-high": { value: "FH" },
      "surrback-front-high-speakers": { value: "FH" },
      "front-wide": { value: "FW" },
      "surrback-front-wide-speakers": { value: "FW" },
      "front-high-front-wide-speakers": { value: "HW" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    MVL: {
      intgrRange: [{ range: "0,100" }],
      "level-up": { value: "UP" },
      "level-down": { value: "DOWN" },
      "level-up-1db-step": { value: "UP1" },
      "level-down-1db-step": { value: "DOWN1" },
      query: { value: "QSTN" }
    },
    TFR: {
      "bass-up": { value: "BUP" },
      "bass-down": { value: "BDOWN" },
      "treble-up": { value: "TUP" },
      "treble-down": { value: "TDOWN" },
      query: { value: "QSTN" }
    },
    TFW: {
      "bass-up": { value: "BUP" },
      "bass-down": { value: "BDOWN" },
      "treble-up": { value: "TUP" },
      "treble-down": { value: "TDOWN" },
      query: { value: "QSTN" }
    },
    TFH: {
      "bass-up": { value: "BUP" },
      "bass-down": { value: "BDOWN" },
      "treble-up": { value: "TUP" },
      "treble-down": { value: "TDOWN" },
      query: { value: "QSTN" }
    },
    TCT: {
      "bass-up": { value: "BUP" },
      "bass-down": { value: "BDOWN" },
      "treble-up": { value: "TUP" },
      "treble-down": { value: "TDOWN" },
      query: { value: "QSTN" }
    },
    TSR: {
      "bass-up": { value: "BUP" },
      "bass-down": { value: "BDOWN" },
      "treble-up": { value: "TUP" },
      "treble-down": { value: "TDOWN" },
      query: { value: "QSTN" }
    },
    TSB: {
      "bass-up": { value: "BUP" },
      "bass-down": { value: "BDOWN" },
      "treble-up": { value: "TUP" },
      "treble-down": { value: "TDOWN" },
      query: { value: "QSTN" }
    },
    TSW: {
      "bass-up": { value: "BUP" },
      "bass-down": { value: "BDOWN" },
      query: { value: "QSTN" }
    },
    SLP: {
      "time-1-90min": { value: "1,90" },
      "time-off": { value: "OFF" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    SLC: {
      test: { value: "TEST" },
      chsel: { value: "CHSEL" },
      up: { value: "UP" },
      down: { value: "DOWN" }
    },
    SWL: {
      "15db-0db-12db": { value: "-15,0,12" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    CTL: {
      "12db-0db-12db": { value: "-12,0,12" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    DIF: {
      "selector-volume": { value: "00" },
      "selector-listening": { value: "01" },
      "02": { value: "02" },
      "03": { value: "03" },
      toggle: { value: "TG" },
      query: { value: "QSTN" }
    },
    DIM: {
      bright: { value: "00" },
      dim: { value: "DIM" },
      dark: { value: "02" },
      "shut-off": { value: "03" },
      "bright-led-off": { value: "08" },
      query: { value: "QSTN" }
    },
    OSD: {
      menu: { value: "MENU" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      right: { value: "RIGHT" },
      left: { value: "LEFT" },
      enter: { value: "ENTER" },
      exit: { value: "EXIT" },
      audio: { value: "AUDIO" },
      video: { value: "VIDEO" },
      home: { value: "HOME" }
    },
    MEM: {
      str: { value: "STR" },
      rcl: { value: "RCL" },
      lock: { value: "LOCK" },
      unlk: { value: "UNLK" }
    },
    IFA: { query: { value: "QSTN" } },
    IFV: { query: { value: "QSTN" } },
    FLD: { query: { value: "QSTN" } },
    SLI: {
      video1: { value: "00" },
      vcr: { value: "00" },
      dvr: { value: "00" },
      video2: { value: "01" },
      cbl: { value: "01" },
      sat: { value: "01" },
      video3: { value: "02" },
      game: { value: "02" },
      video4: { value: "03" },
      aux1: { value: "03" },
      video5: { value: "04" },
      aux2: { value: "04" },
      video6: { value: "05" },
      pc: { value: "05" },
      video7: { value: "06" },
      video8: { value: "07" },
      video9: { value: "08" },
      video10: { value: "09" },
      dvd: { value: "10" },
      bd: { value: "10" },
      stm: { value: "11" },
      tv: { value: "12" },
      tape1: { value: "20" },
      tape: { value: "20" },
      tape2: { value: "21" },
      phono: { value: "22" },
      cd: { value: "23" },
      fm: { value: "24" },
      am: { value: "25" },
      tuner: { value: "26" },
      musicserver: { value: "27" },
      p4s: { value: "27" },
      dlna: { value: "27" },
      internetradio: { value: "28" },
      iradiofavorite: { value: "28" },
      usb1: { value: "29" },
      multich: { value: "30" },
      xm: { value: "31" },
      sirius: { value: "32" },
      dab: { value: "33" },
      universalport: { value: "40" },
      upnp: { value: "40" },
      usb2: { value: "2A" },
      net: { value: "2B" },
      network: { value: "2B" },
      usbt: { value: "2C" },
      bluetooth: { value: "2E" },
      tunein: { value: "NSS01" },
      spotify: { value: "NSS02" },
      deezer: { value: "NSS03" },
      tidal: { value: "NSS04" },
      amazonmusic: { value: "NSS05" },
      chromecast: { value: "NSS06" },
      "dts-play-fi": { value: "NSS07" },
      airplay: { value: "NSS08" },
      alexa: { value: "NSS09" },
      "music-server": { value: "NSS10" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    SLR: {
      dvd: { value: "10" },
      tape: { value: "20" },
      tape2: { value: "21" },
      phono: { value: "22" },
      cd: { value: "23" },
      fm: { value: "24" },
      am: { value: "25" },
      tuner: { value: "26" },
      "music-server": { value: "27" },
      "internet-radio": { value: "28" },
      "multi-ch": { value: "30" },
      xm: { value: "31" },
      source: { value: "80" },
      video1: { value: "00" },
      video2: { value: "01" },
      video3: { value: "02" },
      video4: { value: "03" },
      video5: { value: "04" },
      video6: { value: "05" },
      video7: { value: "06" },
      off: { value: "7F" },
      query: { value: "QSTN" }
    },
    SLA: {
      auto: { value: "00" },
      "multi-channel": { value: "01" },
      analog: { value: "02" },
      ilink: { value: "03" },
      hdmi: { value: "04" },
      coax: { value: "05" },
      opt: { value: "05" },
      balance: { value: "06" },
      arc: { value: "07" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    TGA: { off: { value: "00" } },
    TGB: { off: { value: "00" } },
    TGC: { off: { value: "00" } },
    VOS: {
      d4: { value: "00" },
      component: { value: "01" },
      query: { value: "QSTN" }
    },
    HDO: {
      no: { value: "00" },
      analog: { value: "00" },
      yes: { value: "01" },
      out: { value: "01" },
      "out-sub": { value: "02" },
      sub: { value: "02" },
      both: { value: "05" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    HAO: {
      off: { value: "00" },
      on: { value: "01" },
      auto: { value: "02" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    RES: {
      through: { value: "00" },
      auto: { value: "01" },
      "480p": { value: "02" },
      "720p": { value: "03" },
      "1080i": { value: "04" },
      "1080p": { value: "07" },
      "24fs": { value: "07" },
      "4k-upcaling": { value: "08" },
      source: { value: "06" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    ISF: {
      custom: { value: "00" },
      day: { value: "01" },
      night: { value: "02" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    VWM: {
      auto: { value: "00" },
      "4-3": { value: "01" },
      full: { value: "02" },
      zoom: { value: "04" },
      "smart-zoom": { value: "05" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    VPM: {
      through: { value: "00" },
      custom: { value: "01" },
      cinema: { value: "02" },
      game: { value: "03" },
      "isf-day": { value: "05" },
      "isf-night": { value: "06" },
      streaming: { value: "07" },
      direct: { value: "08" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    LMD: {
      "pure-audio": { value: "11" },
      "pure-direct": { value: "11" },
      multiplex: { value: "12" },
      "full-mono": { value: "13" },
      "extended-mono": { value: "13" },
      "dolby-virtual": { value: "14" },
      "dts-surround-sensation": { value: "15" },
      "audyssey-dsx": { value: "16" },
      "straight-decode": { value: "40" },
      "dolby-ex": { value: "41" },
      "thx-cinema": { value: "42" },
      "thx-surround-ex": { value: "43" },
      "thx-music": { value: "44" },
      "thx-games": { value: "52" },
      "thx-u2": { value: "52" },
      s2: { value: "52" },
      i: { value: "52" },
      "s-cinema": { value: "50" },
      cinema2: { value: "50" },
      "thx-musicmode": { value: "51" },
      "s-music": { value: "51" },
      "s-games": { value: "52" },
      plii: { value: "8B" },
      "pliix-movie": { value: "80" },
      "dolby-surround": { value: "80" },
      "pliix-music": { value: "81" },
      "neo-6-cinema": { value: "82" },
      "neo-x-cinema": { value: "82" },
      "dts-neural:x": { value: "82" },
      "neo-6-music": { value: "83" },
      "neo-x-music": { value: "83" },
      "pliix-thx-cinema": { value: "84" },
      "neo-6": { value: "8C" },
      "neo-x-thx-cinema": { value: "85" },
      "pliix-game": { value: "86" },
      "neural-surr": { value: "87" },
      "neural-thx": { value: "88" },
      "neural-surround": { value: "88" },
      "pliix-thx-games": { value: "89" },
      "pliiz-height": { value: "90" },
      "neo-6-cinema-dts-surround-sensation": { value: "91" },
      "neo-6-music-dts-surround-sensation": { value: "92" },
      "neural-digital-music": { value: "93" },
      "pliiz-height-thx-cinema": { value: "94" },
      "pliiz-height-thx-music": { value: "95" },
      "pliiz-height-thx-games": { value: "96" },
      "pliiz-height-thx-u2": { value: "99" },
      "s2-cinema": { value: "97" },
      "s2-music": { value: "98" },
      "s2-games": { value: "99" },
      stereo: { value: "00" },
      direct: { value: "01" },
      surround: { value: "02" },
      film: { value: "03" },
      "game-rpg": { value: "03" },
      thx: { value: "04" },
      action: { value: "05" },
      "game-action": { value: "05" },
      musical: { value: "06" },
      "game-rock": { value: "06" },
      "mono-movie": { value: "07" },
      orchestra: { value: "08" },
      "dolby-surround-classical": { value: "08" },
      unplugged: { value: "09" },
      "dolby-surround-unplugged": { value: "09" },
      "studio-mix": { value: "0A" },
      "dolby-surround-entertainment-show": { value: "0A" },
      "tv-logic": { value: "0B" },
      "dolby-surround-drama": { value: "0B" },
      "all-ch-stereo": { value: "0C" },
      "extended-stereo": { value: "0C" },
      "theater-dimensional": { value: "0D" },
      "dolby-surround-front-stage-surround": { value: "0D" },
      "enhance-7": { value: "0E" },
      enhance: { value: "0E" },
      "dolby-surround-sports": { value: "0E" },
      "game-sports": { value: "0E" },
      mono: { value: "0F" },
      "whole-house": { value: "1F" },
      "neo-x-thx-games": { value: "8A" },
      "pliix-thx-music": { value: "8B" },
      "neo-x-thx-music": { value: "8C" },
      "neural-thx-cinema": { value: "8D" },
      "neural-thx-music": { value: "8E" },
      "neural-thx-games": { value: "8F" },
      "neo-x-game": { value: "9A" },
      pliix: { value: "A2" },
      "plii-movie-audyssey-dsx": { value: "A0" },
      "plii-music-audyssey-dsx": { value: "A1" },
      "plii-game-audyssey-dsx": { value: "A2" },
      "neo-6-cinema-audyssey-dsx": { value: "A3" },
      "neo-6-music-audyssey-dsx": { value: "A4" },
      "neural-surround-audyssey-dsx": { value: "A5" },
      "neural-digital-music-audyssey-dsx": { value: "A6" },
      "dolby-ex-audyssey-dsx": { value: "A7" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      movie: { value: "MOVIE" },
      music: { value: "MUSIC" },
      game: { value: "GAME" },
      query: { value: "QSTN" }
    },
    LTN: {
      off: { value: "00" },
      "low-dolbydigital": { value: "01" },
      "on-dolby-truehd": { value: "01" },
      "high-dolbydigital": { value: "02" },
      "auto-dolby-truehd": { value: "03" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    RAS: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    ADY: {
      off: { value: "00" },
      on: { value: "01" },
      movie: { value: "01" },
      music: { value: "02" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    ADQ: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    ADV: {
      off: { value: "00" },
      light: { value: "01" },
      medium: { value: "02" },
      heavy: { value: "03" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    DVL: {
      off: { value: "00" },
      low: { value: "01" },
      on: { value: "01" },
      mid: { value: "02" },
      high: { value: "03" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    MOT: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    TUN: {
      "0-in-direct-mode": { value: "0" },
      "1-in-direct-mode": { value: "1" },
      "2-in-direct-mode": { value: "2" },
      "3-in-direct-mode": { value: "3" },
      "4-in-direct-mode": { value: "4" },
      "5-in-direct-mode": { value: "5" },
      "6-in-direct-mode": { value: "6" },
      "7-in-direct-mode": { value: "7" },
      "8-in-direct-mode": { value: "8" },
      "9-in-direct-mode": { value: "9" },
      direct: { value: "DIRECT" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    PRS: {
      intgrRange: { value: "1,40" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    TIP: {
      intgrRange: { value: "1,999" }
    },
    PRM: { "no-1-40": { value: "1,40" } },
    RDS: {
      "00": { value: "00" },
      "01": { value: "01" },
      "02": { value: "02" },
      up: { value: "UP" }
    },
    PTS: { "no-0-30": { value: "0,30" } },
    TPS: { enter: { value: "ENTER" } },
    XCN: { query: { value: "QSTN" } },
    XAT: { query: { value: "QSTN" } },
    XTI: { query: { value: "QSTN" } },
    XCH: {
      intgrRange: [{ range: "0,597" }],
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    XCT: {
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    SCN: { query: { value: "QSTN" } },
    SAT: { query: { value: "QSTN" } },
    STI: { query: { value: "QSTN" } },
    SCH: {
      intgrRange: [{ range: "0,597" }],
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    SCT: {
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    SLK: { input: { value: "INPUT" } },
    HAT: { query: { value: "QSTN" } },
    HCN: { query: { value: "QSTN" } },
    HTI: { query: { value: "QSTN" } },
    HDS: { query: { value: "QSTN" } },
    HPR: { directly: { value: "1,8" } },
    HBL: {
      auto: { value: "00" },
      analog: { value: "01" },
      query: { value: "QSTN" }
    },
    HTS: { mmnnoo: { value: "mmnnoo" } },
    NTC: {
      "0": { value: "0" },
      "1": { value: "1" },
      "2": { value: "2" },
      "3": { value: "3" },
      "4": { value: "4" },
      "5": { value: "5" },
      "6": { value: "6" },
      "7": { value: "7" },
      "8": { value: "8" },
      "9": { value: "9" },
      play: { value: "PLAY" },
      stop: { value: "STOP" },
      pause: { value: "PAUSE" },
      trup: { value: "TRUP" },
      trdn: { value: "TRDN" },
      ff: { value: "FF" },
      rew: { value: "REW" },
      repeat: { value: "REPEAT" },
      random: { value: "RANDOM" },
      display: { value: "DISPLAY" },
      album: { value: "ALBUM" },
      artist: { value: "ARTIST" },
      genre: { value: "GENRE" },
      playlist: { value: "PLAYLIST" },
      right: { value: "RIGHT" },
      left: { value: "LEFT" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      select: { value: "SELECT" },
      delete: { value: "DELETE" },
      caps: { value: "CAPS" },
      location: { value: "LOCATION" },
      language: { value: "LANGUAGE" },
      setup: { value: "SETUP" },
      return: { value: "RETURN" },
      chup: { value: "CHUP" },
      chdn: { value: "CHDN" },
      menu: { value: "MENU" },
      top: { value: "TOP" },
      mode: { value: "MODE" },
      list: { value: "LIST" }
    },
    NAT: { query: { value: "QSTN" } },
    NAL: { query: { value: "QSTN" } },
    NTI: { query: { value: "QSTN" } },
    NTM: {
      "mm-ss-mm-ss": { value: "mm:ss/mm:ss" },
      query: { value: "QSTN" }
    },
    NTR: {
      "cccc-tttt": { value: "cccc/tttt" },
      query: { value: "QSTN" }
    },
    NST: { prs: { value: "prs" } },
    NPR: { "no-1-40": { value: "1,40" } },
    NLS: { ti: { value: "ti" } },
    NJA: { "tp-xx-xx-xx-xx-xx-xx": { value: "tp{xx}{xx}{xx}{xx}{xx}{xx}" } },
    NSV: {},
    NKY: { ll: { value: "ll" } },
    NPU: {},
    NMD: {
      std: { value: "STD" },
      ext: { value: "EXT" },
      vdc: { value: "VDC" },
      query: { value: "QSTN" }
    },
    CCD: {
      "0": { value: "0" },
      "1": { value: "1" },
      "2": { value: "2" },
      "3": { value: "3" },
      "4": { value: "4" },
      "5": { value: "5" },
      "6": { value: "6" },
      "7": { value: "7" },
      "8": { value: "8" },
      "9": { value: "9" },
      "10": { value: "+10" },
      power: { value: "POWER" },
      track: { value: "TRACK" },
      play: { value: "PLAY" },
      stop: { value: "STOP" },
      pause: { value: "PAUSE" },
      "skip-f": { value: "SKIP.F" },
      "skip-r": { value: "SKIP.R" },
      memory: { value: "MEMORY" },
      clear: { value: "CLEAR" },
      repeat: { value: "REPEAT" },
      random: { value: "RANDOM" },
      disp: { value: "DISP" },
      "d-mode": { value: "D.MODE" },
      ff: { value: "FF" },
      rew: { value: "REW" },
      "op-cl": { value: "OP/CL" },
      "d-skip": { value: "D.SKIP" },
      "disc-f": { value: "DISC.F" },
      "disc-r": { value: "DISC.R" },
      disc1: { value: "DISC1" },
      disc2: { value: "DISC2" },
      disc3: { value: "DISC3" },
      disc4: { value: "DISC4" },
      disc5: { value: "DISC5" },
      disc6: { value: "DISC6" },
      stby: { value: "STBY" },
      pon: { value: "PON" }
    },
    CT1: {
      "play-f": { value: "PLAY.F" },
      "play-r": { value: "PLAY.R" },
      stop: { value: "STOP" },
      "rc-pau": { value: "RC/PAU" },
      ff: { value: "FF" },
      rew: { value: "REW" }
    },
    CT2: {
      "play-f": { value: "PLAY.F" },
      "play-r": { value: "PLAY.R" },
      stop: { value: "STOP" },
      "rc-pau": { value: "RC/PAU" },
      ff: { value: "FF" },
      rew: { value: "REW" },
      "op-cl": { value: "OP/CL" },
      "skip-f": { value: "SKIP.F" },
      "skip-r": { value: "SKIP.R" },
      rec: { value: "REC" }
    },
    CEQ: { power: { value: "POWER" } },
    CDT: {
      play: { value: "PLAY" },
      "rc-pau": { value: "RC/PAU" },
      stop: { value: "STOP" },
      "skip-f": { value: "SKIP.F" },
      "skip-r": { value: "SKIP.R" },
      ff: { value: "FF" },
      rew: { value: "REW" }
    },
    CDV: {
      "0": { value: "0" },
      "1": { value: "1" },
      "2": { value: "2" },
      "3": { value: "3" },
      "4": { value: "4" },
      "5": { value: "5" },
      "6": { value: "6" },
      "7": { value: "7" },
      "8": { value: "8" },
      "9": { value: "9" },
      "10": { value: "10" },
      power: { value: "POWER" },
      pwron: { value: "PWRON" },
      pwroff: { value: "PWROFF" },
      play: { value: "PLAY" },
      stop: { value: "STOP" },
      "skip-f": { value: "SKIP.F" },
      "skip-r": { value: "SKIP.R" },
      ff: { value: "FF" },
      rew: { value: "REW" },
      pause: { value: "PAUSE" },
      lastplay: { value: "LASTPLAY" },
      "subton-off": { value: "SUBTON/OFF" },
      subtitle: { value: "SUBTITLE" },
      setup: { value: "SETUP" },
      topmenu: { value: "TOPMENU" },
      menu: { value: "MENU" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      left: { value: "LEFT" },
      right: { value: "RIGHT" },
      enter: { value: "ENTER" },
      return: { value: "RETURN" },
      "disc-f": { value: "DISC.F" },
      "disc-r": { value: "DISC.R" },
      audio: { value: "AUDIO" },
      random: { value: "RANDOM" },
      "op-cl": { value: "OP/CL" },
      angle: { value: "ANGLE" },
      search: { value: "SEARCH" },
      disp: { value: "DISP" },
      repeat: { value: "REPEAT" },
      memory: { value: "MEMORY" },
      clear: { value: "CLEAR" },
      abr: { value: "ABR" },
      "step-f": { value: "STEP.F" },
      "step-r": { value: "STEP.R" },
      "slow-f": { value: "SLOW.F" },
      "slow-r": { value: "SLOW.R" },
      zoomtg: { value: "ZOOMTG" },
      zoomup: { value: "ZOOMUP" },
      zoomdn: { value: "ZOOMDN" },
      progre: { value: "PROGRE" },
      vdoff: { value: "VDOFF" },
      conmem: { value: "CONMEM" },
      funmem: { value: "FUNMEM" },
      disc1: { value: "DISC1" },
      disc2: { value: "DISC2" },
      disc3: { value: "DISC3" },
      disc4: { value: "DISC4" },
      disc5: { value: "DISC5" },
      disc6: { value: "DISC6" },
      foldup: { value: "FOLDUP" },
      folddn: { value: "FOLDDN" },
      "p-mode": { value: "P.MODE" },
      asctg: { value: "ASCTG" },
      cdpcd: { value: "CDPCD" },
      mspup: { value: "MSPUP" },
      mspdn: { value: "MSPDN" },
      pct: { value: "PCT" },
      rsctg: { value: "RSCTG" },
      init: { value: "INIT" }
    },
    CMD: {
      "1": { value: "1" },
      "2": { value: "2" },
      "3": { value: "3" },
      "4": { value: "4" },
      "5": { value: "5" },
      "6": { value: "6" },
      "7": { value: "7" },
      "8": { value: "8" },
      "9": { value: "9" },
      power: { value: "POWER" },
      play: { value: "PLAY" },
      stop: { value: "STOP" },
      ff: { value: "FF" },
      rew: { value: "REW" },
      "p-mode": { value: "P.MODE" },
      "skip-f": { value: "SKIP.F" },
      "skip-r": { value: "SKIP.R" },
      pause: { value: "PAUSE" },
      rec: { value: "REC" },
      memory: { value: "MEMORY" },
      disp: { value: "DISP" },
      scroll: { value: "SCROLL" },
      "m-scan": { value: "M.SCAN" },
      clear: { value: "CLEAR" },
      random: { value: "RANDOM" },
      repeat: { value: "REPEAT" },
      enter: { value: "ENTER" },
      eject: { value: "EJECT" },
      "10-0": { value: "10/0" },
      name: { value: "NAME" },
      group: { value: "GROUP" },
      stby: { value: "STBY" }
    },
    CCR: {
      "1": { value: "1" },
      "2": { value: "2" },
      "3": { value: "3" },
      "4": { value: "4" },
      "5": { value: "5" },
      "6": { value: "6" },
      "7": { value: "7" },
      "8": { value: "8" },
      "9": { value: "9" },
      power: { value: "POWER" },
      "p-mode": { value: "P.MODE" },
      play: { value: "PLAY" },
      stop: { value: "STOP" },
      "skip-f": { value: "SKIP.F" },
      "skip-r": { value: "SKIP.R" },
      pause: { value: "PAUSE" },
      rec: { value: "REC" },
      clear: { value: "CLEAR" },
      repeat: { value: "REPEAT" },
      "10-0": { value: "10/0" },
      scroll: { value: "SCROLL" },
      "op-cl": { value: "OP/CL" },
      disp: { value: "DISP" },
      random: { value: "RANDOM" },
      memory: { value: "MEMORY" },
      ff: { value: "FF" },
      rew: { value: "REW" },
      stby: { value: "STBY" }
    },
    CPT: {
      "0": { value: "0" },
      "1": { value: "1" },
      "2": { value: "2" },
      "3": { value: "3" },
      "4": { value: "4" },
      "5": { value: "5" },
      "6": { value: "6" },
      "7": { value: "7" },
      "8": { value: "8" },
      "9": { value: "9" },
      "10": { value: "10" },
      setup: { value: "SETUP" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      left: { value: "LEFT" },
      right: { value: "RIGHT" },
      enter: { value: "ENTER" },
      return: { value: "RETURN" },
      disp: { value: "DISP" },
      play: { value: "PLAY" },
      stop: { value: "STOP" },
      pause: { value: "PAUSE" },
      "skip-f": { value: "SKIP.F" },
      "skip-r": { value: "SKIP.R" },
      ff: { value: "FF" },
      rew: { value: "REW" },
      repeat: { value: "REPEAT" },
      shuffle: { value: "SHUFFLE" },
      prsup: { value: "PRSUP" },
      prsdn: { value: "PRSDN" },
      mode: { value: "MODE" }
    },
    IAT: { query: { value: "QSTN" } },
    IAL: { query: { value: "QSTN" } },
    ITI: { query: { value: "QSTN" } },
    ITM: {
      "mm-ss-mm-ss": { value: "mm:ss/mm:ss" },
      query: { value: "QSTN" }
    },
    ITR: {
      "cccc-tttt": { value: "cccc/tttt" },
      query: { value: "QSTN" }
    },
    IST: { prs: { value: "prs" } },
    ILS: {},
    IMD: {
      std: { value: "STD" },
      ext: { value: "EXT" },
      vdc: { value: "VDC" },
      query: { value: "QSTN" }
    },
    UTN: {
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    UPR: {
      "no-1-40": { value: "1,40" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    UPM: { intgrRange: [{ range: "1,40" }] },
    UHP: { directly: { value: "1,8" } },
    UHB: {
      auto: { value: "00" },
      analog: { value: "01" },
      query: { value: "QSTN" }
    },
    UHA: { query: { value: "QSTN" } },
    UHC: { query: { value: "QSTN" } },
    UHT: { query: { value: "QSTN" } },
    UHD: { query: { value: "QSTN" } },
    UHS: { mmnnoo: { value: "mmnnoo" } },
    UDS: { query: { value: "QSTN" } },
    UDD: {
      pt: { value: "PT" },
      at: { value: "AT" },
      mn: { value: "MN" },
      mf: { value: "MF" },
      up: { value: "UP" }
    },
    ADM: {
      off: { value: "00" },
      on: { value: "01" },
      tg: { value: "TG" },
      query: { value: "QSTN" }
    },
    AEQ: {
      off: { value: "00" },
      "on-on-all-ch": { value: "01" },
      "on-ex-front-l-r": { value: "02" },
      "on-front-matching-eq": { value: "03" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    APD: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    APS: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    ARC: {
      off: { value: "00" },
      auto: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    ASC: {
      auto: { value: "00" },
      manual: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    AVS: {
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    BCS: {
      charging: { value: "00" },
      completed: { value: "01" },
      low: { value: "10" },
      middle: { value: "11" },
      high: { value: "12" },
      query: { value: "QSTN" }
    },
    CCM: {
      main: { value: "01" },
      zone2: { value: "02" },
      sub: { value: "10" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    CEC: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    DSS: {
      off: { value: "C00" },
      slot1: { value: "C01" },
      slot2: { value: "C02" },
      slot3: { value: "C03" },
      query: { value: "QSTN" }
    },
    FXP: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    HBT: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    HSF: {
      "4k-standard": { value: "00" },
      "4k-enhanced": { value: "01" },
      "8k-standard": { value: "02" },
      "8k-enhanced": { value: "03" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    LDM: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    },
    LFE: {
      "0dB": { value: "00" },
      "-1dB": { value: "01" },
      "-2dB": { value: "02" },
      "-3dB": { value: "03" },
      "-4dB": { value: "04" },
      "-5dB": { value: "05" },
      "-10dB": { value: "0A" },
      "-15dB": { value: "0F" },
      "-20dB": { value: "14" },
      "-oodB": { value: "FF" },
      up: { value: "UP" },
      down: { value: "DOWN" },
      query: { value: "QSTN" }
    },
    LPS: {
      off: { value: "00" },
      on: { value: "01" },
      up: { value: "UP" },
      query: { value: "QSTN" }
    }
  }
};
